### ISSUE TITLE
Consider adding Aerolith WordVault

### ISSUE THREAD

**Issue by domino14** [open-spaced-repetition/awesome-fsrs#10]
Hi all, I am wondering if you would consider adding WordVault. This is a spaced repetition app to learn words for the game of Scrabble.

The source code is here: https://github.com/domino14/word_db_server/tree/master/internal/wordvault and it uses the go-fsrs library. The app can be played at https://aerolith.org/wordvault

Thank you.

**Comment by L-M-Sherlock** [comment]
PR is welcome!
